version: "3.8"

services:
  geoserver:
    container_name: geoserver
    build:
      context: ./build_geoserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver_data:/geoserver
    depends_on:
      - postgis

  postgis:
    container_name: postgis
    image: postgis/postgis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx-proxy:
    container_name: proxy
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - webroot:/var/www/letsencrypt
    env_file:
      - .env
    depends_on:
      - geoserver

  certbot:
    container_name: certbot
    build:
      context: ./build_certbot
    depends_on:
      - nginx-proxy
    volumes:
      - webroot:/var/www/letsencrypt

    command: certbot certonly -a webroot --webroot-path=/var/www/letsencrypt -m christian.trapp@gbv.de --agree-tos -d geodienste.gbv.de


volumes:
  db_data:
  webroot:
