version: "3.8"

services:
  geoserver:
    container_name: geoserver
    build:
      context: ./build_geoserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver_data:/geoserver
    depends_on:
      - postgis

  postgis:
    container_name: postgis
    image: postgis/postgis:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
