version: "3.8"

services:
  geoserver:
    build:
      context: ./build_geoserver
    restart: unless-stopped
    volumes:
      - ./geoserver_data:/geoserver
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8080:8080"
      - "443:443"

  postgis:
    image: postgis/postgis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

