version: "3.8"

services:
  geoserver:
    build:
      context: ./build_geoserver
    restart: unless-stopped
    volumes:
      - ./geoserver_data:/geoserver
      - /etc/letsencrypt:/etc/letsencrypt

  postgis:
    image: postgis/postgis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/app/app/static/
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    depends_on:
      - geoserver

  letsencrypt:
    restart: unless-stopped
    container_name: letsencrypt
    env_file:
      - .env
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

volumes:
  db_data:
  html:
  certs:
  vhost:
  static:
